
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#Количество начальных жителей. [По умолчанию: 4, мин: 1, макс: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#Нужно ли протянуть строительную ленту вокруг зоны строительства? [По умолчанию: true]
	builderplaceconstructiontape = true
	#Могут ли игроки размещать бесконечное количество лагерей/кораблей снабжения? [По умолчанию: false]
	allowinfinitesupplychests = false
	#Разрешено ли игрокам покидать свои колонии, чтобы легко создавать новые? Примечание: Может вызвать баги! [По умолчанию: false]
	allowinfinitecolonies = false
	#Разрешить колонии в других мирах? [По умолчанию: true]
	allowotherdimcolonies = true
	#Если количество жителей в колонии меньше начального, то это повлияет на время появления нового жителя. [По умолчанию: 60, мин: 10, макс: 600]
	#Range: 10 ~ 600
	citizenrespawninterval = 60
	#Максимальное число жителей в одной колонии. [По умолчанию: 250, мин: 4, макс: 500]
	#Range: 4 ~ 500
	maxcitizenpercolony = 250
	#Задержка после установки каждого блока (увеличение значения увеличивает задержку). [По умолчанию: 15, мин: 1, макс: 500]
	#Range: 1 ~ 500
	builderbuildblockdelay = 15
	#Модификатор задержки для добычи блока (уменьшение значения уменьшает задержку). [По умолчанию: 500, мин: 1, макс: 10000]
	#Range: 1 ~ 10000
	blockminingdelaymodifier = 500
	#Включить функции разработчика (могут возникнуть баги)? [По умолчанию: false]
	enableindevelopmentfeatures = false
	#Должны ли быть отрисованы имена жителей? [По умолчанию: true]
	alwaysrendernametag = true
	#Работают ли жители во время дождя? [По умолчанию: false]
	workersalwaysworkinrain = false
	#Отправлять игрокам уведомления о входе/выходе из колонии? [По умолчанию: true]
	sendenteringleavingmessages = true
	#Разрешить игрокам изменять имена граждан? -1 если нет, 0 для определённых игроков, 1 если да. (Для установки людей, которые могут изменять имена, смотрите "Группы Специальных Разрешений" ниже.) [По умолчанию: 1, мин: -1, макс: 1]
	#Range: -1 ~ 1
	allowglobalnamechanges = 1
	#Должен ли отображаться специальный праздничный контент? [По умолчанию: true]
	holidayfeatures = true
	#Количество земли на одну заправку компоста. [По умолчанию: 1, мин: 0, макс: 100]
	#Range: 0 ~ 100
	dirtfromcompost = 1
	#Шансы Шахтера получить руду при добыче булыжника или камня (по умолчанию, можно увеличить с помощью датапаков на другие материалы). В %. (Чтобы изменить список руд, которые может найти Шахтер, см. "Список Счастливых Руд".) [По умолчанию: 1, мин: 0, макс: 100]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#Минимальный уровень Ратуши, необходимый, чтобы разрешить телепортацию к союзным колониям. [По умолчанию: 3, мин: 0, макс: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Предложить использовать жезл строителя, когда размещается постройка без него. [По умолчанию: true]
	suggestbuildtoolplacement = true
	#Модификатор потребления пищи. [По умолчанию: 1,000000, мин: 0,100000, макс: 100,000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#Частота болезней. 1 = Очень частые, 100 = чрезвычайно редкие. [По умолчанию: 5, мин: 1, макс: 100]
	#Range: 1 ~ 100
	diseasemodifier = 5
	#Если часть колонии загружена владельцем/сотрудником, должна ли колония оставаться загруженной? (Установите количество загружаемых кусков с помощью параметра "Строгость загрузки частей колонии"). [По умолчанию: false]
	forceloadcolony = false
	#Настройте, как долго чанки остаются загруженными после того, как игрок покидает игру. По умолчанию: 10 минут. [По умолчанию: 10, мин: 1, макс: 1440]
	#Range: 1 ~ 1440
	loadtime = 10
	#Это контролирует, сколько блоков загружается с опцией «Загрузка чанков колонии». Чем выше это значение, тем меньше чанков будет загружено. (Внутренние чанки будут загружены первыми.) 1 = загрузить все занятые чанки. [По умолчанию: 3, мин: 1, макс: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#Шанс того, что в Таверну зайдёт злой посетитель, который сбежит с вашими ресурсами, в %. [По умолчанию: 2, мин: 1, макс: 100]
	#Range: 1 ~ 100
	badvisitorchance = 2
	#Максимальное количество брёвен в одном дереве, которое лесоруб может проверить во время поиска дерева. [По умолчанию: 400, мин: 1, макс: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#Отключает ограничения на размещение лагерей снабжения, предназначенные для парящих миров и подобных [По умолчанию: false]
	nosupplyplacementrestrictions = false
	#Рейдеры будут появляться в небе, если эта функция включена [По умолчанию: false]
	skyraiders = false

#Вся конфигурация, относящаяся к системе исследований
[research]
	#Позволяет автоматически и (почти) мгновенно завершать исследования для игроков в творческом режиме. Если false, творческие игроки все равно смогут начать исследования, но будут иметь нормальные темпы прогресса. [По умолчанию: true]
	researchcreativecompletion = true
	#Значительно увеличивает количество информации, связанной с исследовательскими датапаками, которая регистрируется во время загрузки мира. [По умолчанию: false]
	researchdebuglog = false
	#Список предметов, которые нужно тратить игрокам при отмене уже завершенного исследования. 
	researchresetcost = ["minecolonies:ancienttome:1"]

#Все конфигурации, связанные с командами MineColonies
[commands]
	#Могут ли игроки использовать команду /mc rtp? [По умолчанию: false]
	canplayerusertpcommand = false
	#Могут ли игроки использовать команду /mc colony teleport? [По умолчанию: false]
	canplayerusecolonytpcommand = false
	#Могут ли игроки телепортироваться в колонии союзников? [По умолчанию: true]
	canplayeruseallytownhallteleport = true
	#Позволять ли игрокам использовать команду /mc home? Примечание: ее могут использовать только владельцы колонии. [По умолчанию: false]
	canplayerusehometpcommand = false
	#Позволить игроку использовать команду /mc colony info command? [По умолчанию: true]
	canplayeruseshowcolonyinfocommand = true
	#Позволить игроку использовать команду /mc citizens kill? [По умолчанию: false]
	canplayerusekillcitizenscommand = false
	#Позволить игроку использовать команду /mc colony addOfficer? [По умолчанию: true]
	canplayeruseaddofficercommand = true
	#Позволить игроку использовать команду /mc colony delete? [По умолчанию: true]
	canplayerusedeletecolonycommand = true
	#Количество попыток найти безопасный случайный портал (через /mc rtp). [По умолчанию: 4, мин: 1, макс: 10]
	#Range: 1 ~ 10
	numberofattemptsforsafetp = 4

#Вся конфигурация, относящиеся к требованиям колонии
[claims]
	#Максимальный размер колоний. Это радиус, измеряемый в чанках. [По умолчанию: 20, мин: 1, макс: 250]
	#Range: 1 ~ 250
	maxColonySize = 20
	#Минимальное расстояние (в чанках) между колониями. [По умолчанию: 8, мин: 1, макс: 200]
	#Range: 1 ~ 200
	minColonyDistance = 8
	#Начальный размер колоний. Это радиус, измеряемый в чанках. [По умолчанию: 4, мин: 1, макс: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#Должно ли мин./макс. расстояние от спавна также влиять на размещение колоний? [По умолчанию: false]
	restrictcolonyplacement = false
	#Максимальное расстояние (в блоках) от мирового спауна для колонии. [По умолчанию: 8000, мин: 1000, макс: 100000]
	#Range: 1000 ~ 100000
	maxdistancefromworldspawn = 8000
	#Минимальное расстояние (в блоках) от мирового спауна для колонии. [По умолчанию: 512, мин: 1, макс: 1000]
	#Range: 1 ~ 1000
	mindistancefromworldspawn = 512
	#Будут ли офицеры этой колонии получать достижения? [По умолчанию: true]
	officersreceiveadvancements = true

#Вся конфигурация боевых элементов MineColonies
[combat]
	#Спавнить рейдеров или нет. [По умолчанию: true]
	dobarbariansspawn = true
	#Настройки сложности для рейдеров. [По умолчанию: 5, мин: 0, макс: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#Максимальный размер армии рейдеров. [По умолчанию: 80, мин: 6, макс: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 80
	#Whether or not raiders can break through obstacles [По умолчанию: true]
	dobarbariansbreakthroughwalls = true
	#Среднее количество ночей между рейдами. [По умолчанию: 14, мин: 1, макс: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#Минимальное количество ночей между рейдами. [По умолчанию: 10, мин: 1, макс: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#Должны ли мобы нападать на жителей? [По умолчанию: true]
	mobattackcitizens = true
	#Могут ли рейдеры взломать двери. [По умолчанию: true]
	shouldraiderbreakdoors = true
	#Должны ли жители звать стражу в случае нападения на них? [По умолчанию: true]
	citizencallforhelp = true
	#Множитель урона для стражей-лучников. [По умолчанию: 1,000000, мин: 0,100000, макс: 5,000000]
	#Range: 0.1 ~ 5.0
	rangerdamagemult = 1.0
	#Множитель урона для Рыцарей стражи. [По умолчанию: 1,000000, мин: 0,100000, макс: 5,000000]
	#Range: 0.1 ~ 5.0
	knightdamagemult = 1.0
	#Множитель здоровья для всех стражников. [По умолчанию: 1,000000, мин: 0,100000, макс: 5,000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#Включить PVP режим (колонии могут быть разрушены и разграблены при выполнении определенных условий). [По умолчанию: false]
	pvp_mode = false
	#Число дней перед деспавном пиратского корабля. [По умолчанию: 3, мин: 1, макс: 10]
	#Range: 1 ~ 10
	daysuntilpirateshipsdespawn = 3
	#Максимальный Y уровень (высота) для спавна рейдеров. [По умолчанию: 200, мин: 1, макс: 500]
	#Range: 1 ~ 500
	maxyforbarbarians = 200

#Все параметры настроек доступа
[permissions]
	#Включить защиту колоний? [По умолчанию: true]
	enablecolonyprotection = true
	#Установите макс. значение резервных копий [По умолчанию: 50, мин: 3, макс: 5000]
	#Range: 3 ~ 5000
	maxkeptbackups = 50
	#Независимо от защиты колонии, следует ли выключать взрывы внутри колоний? "Нет урона" полностью отключает взрывы. "Урон только по игрокам" позволяет взрывам наносить урон игрокам и враждебным мобам, но не блокам и нейтральным или дружелюбным мобам. "Урон существам" позволяет наносить урон всем мобам. "Урон всему" позволяет наносить урон всем мобам и блокам. 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#Игроки с особыми разрешениями, в частности на изменение имен граждан (см. "Изменение Имен" выше). 
	specialpermgroup = ["_Raycoms_"]
	#Блоки с которыми пользователи должны иметь возможность взаимодействовать в любой колонии (искл: торговый автомат) 
	freetointeractblocks = ["dirt", "0 0 0"]
	#Количество секунд между сообщениями о разрешении (для минимизации спама). [По умолчанию: 30, мин: 1, макс: 1000]
	#Range: 1 ~ 1000
	secondsBetweenPermissionMessages = 30

#Все настройки, связанные с совместимостью мода
[compatibility]
	#Предметы используемые жителями в библиотеке. 
	configliststudyitems = ["minecraft:paper;400;100", "minecraft:book;600;10"]
	#Вещи, нужные посетителям Таверны. 
	configlistrecruitmentitems = ["minecraft:hay_block;3", "minecraft:book;2", "minecraft:enchanted_book;9", "minecraft:diamond;9", "minecraft:emerald;8", "minecraft:baked_potato;1", "minecraft:gold_ingot;2", "minecraft:redstone;2", "minecraft:lapis_lazuli;2", "minecraft:cake;11", "minecraft:sunflower;5", "minecraft:honeycomb;6", "minecraft:quartz;3"]
	#Список блоков руды, редко обнаруживаемых шахтерами магическим способом (см. «Шанс руды»). Включает блок и его шанс, разделенные восклицательными знаками. 
	luckyores = ["minecraft:coal_ore!64", "minecraft:copper_ore!48", "minecraft:iron_ore!32", "minecraft:gold_ore!16", "minecraft:redstone_ore!8", "minecraft:lapis_ore!4", "minecraft:diamond_ore!2", "minecraft:emerald_ore!1"]
	#Размер ствола для динамичных деревьев, который может рубить лесник: 1-8. [По умолчанию: 5, мин: 1, макс: 8]
	#Range: 1 ~ 8
	dynamictreeharvestsize = 5
	#Смещение для максимальной прочности для не зачарованной удочки, которая может использоваться в хижине рыболова второго уровня, сравнивается с другими железными инструментами (250). Удочки из Thermal Foundation требуют +6. Хижина рыбака третьего уровня может использовать не зачарованные удочки любого уровня прочности до тех пор, пока они вообще могут получать урон. Всё что ниже -250 позволяет использовать только ванильные палки, за исплючением тех, что разрешены первым уровнем. [По умолчанию: 6, мин: -249, макс: 250000]
	#Range: -249 ~ 250000
	fishingroddurabilityadjustt2 = 6
	#Смещение для максимальной прочности для не зачарованной удочки, которая может использоваться в хижине рыболова первого уровня, сравнивается с другими деревянными инструментами (59). Ванильные удочки работают всегда, но эквивалентам потребуется +6. По умолчанию допускаются значения до серебряных из Thermal Foundation. Все что ниже -59, допускает только ванильные палки. [По умолчанию: 22, мин: -58, макс: 250000]
	#Range: -58 ~ 250000
	fishingroddurabilityadjustt1 = 22
	#Все болезни, которые граждане могут получить. Название, как часто встречается, и все ингредиенты для его лечения. 
	diseases = ["Influenza,100,minecraft:carrot,minecraft:potato", "Measles,10,minecraft:dandelion,minecraft:kelp,minecraft:poppy", "Smallpox,1,minecraft:honey_bottle,minecraft:golden_apple"]
	#При загрузке рецептов генерируйте CSV-файлы аудита, чтобы помочь в отладке пакетов данных или дополнительных модов. [По умолчанию: false]
	auditcraftingtags = false
	#Включить отладку инвентаря. [По умолчанию: false]
	debuginventories = false
	#Включите это, если вы используете этот мир для создания и сканирования чертежей. [По умолчанию: false]
	blueprintbuildmode = false

#Все настройки, связанные с поиском пути
[pathfinding]
	#Детализация отладочных сообщений поиска пути. [По умолчанию: 0, мин: 0, макс: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Минимальное число последовательных рельс для жителей, которыми они могут пользоваться. [По умолчанию: 8, мин: 5, макс: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#Количество дополнительных потоков, которые будут использоваться для поиска пути. [По умолчанию: 2, мин: 1, макс: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#Все настройки, связанные с системой запросов
[requestSystem]
	#Максимальное число попыток, чтобы система запросов выполнила действие повторно. Более высокий уровень увеличит нагрузку на сервер. [По умолчанию: 3, мин: 1, макс: 10]
	#Range: 1 ~ 10
	maximalretries = 3
	#Количество тиков между попытками системы запросов для повторяемых запросов. Понижение значения увеличивает нагрузку на сервер. [По умолчанию: 1200, мин: 30, макс: 10000]
	#Range: 30 ~ 10000
	delaybetweenretries = 1200
	#Должна ли система запросов творчески подходить к решению (если возможно), когда игроку требуется решить запрос? Это инструмент отладки и он может занять много времени для решения запроса. [По умолчанию: false]
	creativeresolve = false
	#Позволить игроку использовать команду /mc colony requestsystem-reset? [По умолчанию: false]
	canplayeruseresetcommand = false

